config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
    get 'account/profile/edit', to: 'devise/registrations#edit'
    patch 'account/profile', :as => :user_root
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :weapons, only: [ :index, :show] do
    resources :bookings, only: [:new, :create]
  end

  # get "/bookings/:id/reject",  to: "bookings#reject", as: "accept_booking"
  # get "/bookings/:id/accept",  to: "bookings#accept", as: "reject_booking"

  namespace :account do
    # get "/",             to: "profile#show"
    # get "/bookings",     to: "profile#bookings"
    # get "/reservings",   to: "profile#reservings"
    # get "/weapons",      to: "profile#weapons"

    resource :profile, only: [:show]
    resources :bookings_made_by_me, only: [:index, :show]
    resources :bookings_made_to_me, only: [:index, :show] do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :weapons, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :weapon
  belongs_to :hirer, class_name: "User"

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: ["pending", "accepted", "rejected"], allow_nil: false }
  validates :hirer_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings, dependent: :destroy, foreign_key: :hirer_id
  has_many :weapons, foreign_key: :owner_id, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  # weapons category are defined again in weapon controller
  weapons_category = %w(pistols riffles knives heavy shotguns swords)

  belongs_to :owner, class_name: "User"
  has_many :bookings, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true, inclusion: { in: weapons_category, allow_nil: false }
  validates :price, presence: true
end

app/controllers/account/bookings_made_by_me_controller.rb
class Account::BookingsMadeByMeController < ApplicationController
  before_action :find_booking_made_by_me, only: [:show]

  def index
    @bookings_made_by_me = Booking.where(hirer_id: current_user.id)
  end

  def show
    @weapon = Weapon.find(@booking.weapon_id)
    @number_of_days = (@booking.end_date - @booking.start_date).to_i
    @total_price = @number_of_days * @weapon.price
  end

  private

  def find_booking_made_by_me
    @booking = Booking.find(params[:id])
  end
end

app/controllers/account/bookings_made_to_me_controller.rb
class Account::BookingsMadeToMeController < ApplicationController
  before_action :find_booking_made_to_me, only: [:show, :accept, :reject]

  def index
    @my_weapons = Weapon.where(owner_id: current_user.id)
    @bookings_made_to_me = []
    @my_weapons.each do |weapon|
      booking_made_by_me = Booking.where(weapon_id: weapon.id)
      @bookings_made_to_me << booking_made_by_me
    end
  end

  def show
    @weapon = Weapon.find(@booking.weapon_id)
    @number_of_days = (@booking.end_date - @booking.start_date).to_i
    @total_price = @number_of_days * @weapon.price
  end

  def accept
    @booking.status = "accepted"
    @booking.save
    redirect_to account_bookings_made_to_me_index_path
  end

  def reject
    @booking.status = "rejected"
    @booking.save
    redirect_to account_bookings_made_to_me_index_path
  end

  private

  def find_booking_made_to_me
    @booking = Booking.find(params[:id])
  end
end

app/controllers/account/profiles_controller.rb
class Account::ProfilesController < ApplicationController

  def show
  end
  
end

app/controllers/account/weapons_controller.rb
class Account::WeaponsController < ApplicationController
  def index
    @weapons = Weapon.where(owner_id: current_user.id)
  end

  def new
    @weapon = Weapon.new
  end

  def create
   @weapon = Weapon.new(weapon_params)
   @weapon.owner_id = current_user.id
   if @weapon.save
    redirect_to weapon_path(@weapon)
  else
    render :new
  end
 end

 private

 def weapon_params
  params.require(:weapon).permit(:title, :description, :category, :price, :availability, :photo, :photo_cache)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar_url])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar_url])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show]
  skip_before_action :authenticate_user!, only: :new

  def show
  end

  def new
    @booking = Booking.new(booking_params)
    @weapon = Weapon.find(params[:weapon_id])
    @start_date = DateTime.strptime(booking_params[:start_date], '%m/%d/%Y').to_date
    @end_date = DateTime.strptime(booking_params[:end_date], '%m/%d/%Y').to_date
    @number_of_days = (@end_date - @start_date).to_i
    if @number_of_days <= 0
      flash[:alert] = "Wrong dates: end date must be superior to start date"
      redirect_to weapon_path(@weapon)
    else
      @total_price = @weapon.price * @number_of_days
    end
  end

  def create
    @weapon = Weapon.find(params[:weapon_id])
    @booking = Booking.new(booking_params)
    @number_of_days = (@booking.end_date - @booking.start_date).to_i
    @total_price =  @number_of_days * @weapon.price
    if @booking.save
      redirect_to account_bookings_made_by_me_path(@booking)
      flash[:notice] = "Your booking request has been sent to the owner"
    else
      redirect_to weapon_path(@weapon)
      flash[:notice] = "Your booking has failed, please try again"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :hirer_id, :weapon_id, :status)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @weapons = Weapon.last(4)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :find_weapon, only: [:show]
  skip_before_action :authenticate_user!

  def index
    @weapons_category = %w(pistols riffles knives heavy shotguns swords)
    @weapons = Weapon.all

    query_hash = query_hash_builder(params)

    if query_hash[:category].present?
      @weapons = @weapons.where(category: query_hash[:category])
    end

    if query_hash["min-price"].present?
      @weapons = @weapons.where("price >= ?", query_hash["min-price"].to_i)
    end

    if query_hash["max-price"].present?
      @weapons = @weapons.where("price <= ?", query_hash["max-price"].to_i)
    end

    if query_hash[:query].present?
      @weapons = @weapons.where("LOWER(title) LIKE ?", "%#{query_hash[:query].downcase}%")
    end
  end

  def show
  end

  private

  def query_hash_builder(params_hash)
    query_hash = {}
    query_hash[:query] = params_hash[:query]
    query_hash["min-price"] = params_hash["min-price"]
    query_hash["max-price"] = params_hash["max-price"]
    query_hash[:category] = params_hash[:category]
    query_hash[:category] == "all" ? query_hash[:category] = "" : query_hash[:category] =   query_hash[:category]
    query_hash.delete_if { |k, value| value == "" }
    return query_hash
  end

  def find_weapon
    @weapon = Weapon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/total_price.rb
  def number_of_days(booking)
    Math.round(booking.end_date - booking.start_date)
  end

  def total_price(booking)
    @price = Weapon.find(booking.weapon_id).price
    @total_price = @price * number_of_days(booking)
  end

app/views/bookings/new.html.erb
<% content_for :title, "Lord of War - New booking" %>

<div class="container text-center" id="top">
  <div class="row col-xs-12 col-sm-9 col-sm-offset-3 ">
    <h2 class="title">Your booking details<h2>
      <div class="container-card">
        <div class="wrapper">

         <div class="header">
          <div class="price">
            <h1>€ <%= number_with_delimiter(@total_price) %> for <%= @number_of_days %> days </h1>
          </div>
          <div class="heart-wrap">
            <a href="#"><i class="fa heart"></i></a>
          </div>
        </div>
        <div class="product">
          <%= image_tag("#{@weapon.photo_url}", class: "img") %>
        </div>

        <div class="info">
          <div class="title">
            <h1><%= @weapon.title %></h1>
            <p><%= @weapon.description %></p>
            <div class="booking_info text-center">

              <ul class="list-group list-booking">
                <li class="list-group-item"><h5><strong>Starting date: </strong><%= @start_date %></h5></li>
                <li class="list-group-item"><h5><strong>Ending date: </strong><%= @end_date %></h5></li>
                <li class="list-group-item"><h5><strong>Total number of days: </strong><%= @number_of_days%> </h5></li>
                <li class="list-group-item"><h5><strong>Price / day: </strong> € <%= number_with_delimiter(@weapon.price) %></h5></li>
                <li class="list-group-item"><h5><strong>Total price: </strong> € <%= number_with_delimiter(@total_price) %></h5></li>
                <li class="list-group-item"><h5><strong>Available: </strong><%= @weapon.availability %></h5></li>
              </ul>

            </div>
          </div>

          <%= simple_form_for [@weapon, @booking] do |f| %>
          <%= f.hidden_field :start_date, value: @start_date %>
          <%= f.hidden_field :end_date, value: @end_date %>
          <%= f.hidden_field :hirer_id, value: current_user.id %>
          <%= f.hidden_field :weapon_id, value: @weapon.id %>
          <%= f.hidden_field :status, value: "pending" %>
          <%= f.submit "Ask for booking", class: "askBtn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class= "row col-xs-12 col-sm-3">
    <h2 tag="title-owner">Owner</h2>
    <div class="container-card-right">
      <div class="wrapper">

        <div class="avatar-lg">
          <%= image_tag("#{User.find(@weapon.owner_id).avatar_url}") %>
        </div>

        <div class="info">
          <div class="title-user">
            <h2><%= User.find(@weapon.owner_id).last_name%></h2>
            <h4><%= User.find(@weapon.owner_id).first_name %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :title, "Lord of War - Home" %>


<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),
                            url('<%= image_path 'home-bg.jpg' %>');">
  <div class="banner-content">
    <h1>Welcome on Lord of War</h1>
    <p>Find your dream weapon</p>
    <form action="weapons" method="get" class="form-inline">
      <input name="query" id="query" type="text" class="form-control input-lg black-color" placeholder="Show all weapons"/>
      <input type="submit" value="Go!" class="btn btn-primary btn-lg"/>
    </form>
    <a class="last-arrow-link" href="#last-weapons"><%= image_tag 'down-arrow.png' %></a>
  </div>
</div>

<div id="last-weapons" class="container">
  <div class="row">
    <h2>Last weapons put online :</h2>
    <% @weapons.each do |weapon| %>
    <div class="col-xs-12 col-sm-3">
      <%= link_to weapon_path(weapon.id) do %>
      <div class="card">
        <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
        url('<%= image_path weapon.photo %>');"></div>
        <div class="card-description">
          <div class="card-price"><%= "#{number_with_delimiter(weapon.price)} €" %></div>
          <div class="card-title"><%= weapon.title %></div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<div class="container" id="features">
  <h1 class="text-center">Handle what you want</h1>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag 'COD_BO2_Ray_Gun_r.png', class: "feature-img" %></p>
    <h2 class="text-center">Discover</h2>
    <p class="text-center">Discover unseen and unused weapons</p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag 'beer.png', class: "feature-img" %></p>
    <h2 class="text-center">Share</h2>
    <p class="text-center">Share a common passion with users here</p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag 'dollar.png', class: "feature-img" %></p>
    <h2 class="text-center">Save money</h2>
    <p class="text-center">No need to buy a weapon to be disapointed aftermath</p>
  </div>
</div>

<div class="container" id="howto">
  <h1 class="text-center">Easy to use</h1>
  <p>Step 1, Step 2.... Put screenshoot or things like that</p>
</div>

<div class="container" id="faq">
  <h1 class="text-center">FAQ and testimonies</h1>
  <div class="faq">
    <p>Is that legal?</p>
    <p>100%</p>
    <p></p>
    <p>Is that safe?</p>
    <p>100%</p>
    <p></p>
    <p>Is that cool?</p>
    <p>Super much very very cool and beyond</p>
  </div>
  <div class="reviews">
    <p>Put twitter cards or stuff like that</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<!-- notice -> flash[:notice]
alert -> flash[:alert]
 -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Post an ad -->
    <%= link_to "Rent your weapon", new_account_weapon_path, class: "navbar-wagon-item btn btn-treehouse", style: "background-image: url('#{image_path 'btn-post-ad.jpg'}'); background-size: cover; opacity: 0.8" %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to account_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to account_profile_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/weapons/index.html.erb
<% content_for :title, "Lord of War - Weapons" %>

<div id="top-wrapper">
  <div class="row">
    <div class="col-xs-12">
      <h1>Find your dream weapon</h1>
      <br>
      <div id="filters">
        <form action="#" method="get" class="form-inline">
          <label for="query" class="query-label">Weapons to find :</label>
          <input name="query" id="query" type="text" value="<%= params[:query] %>"/>

          <label for="min-price" class="min-price-label">Min price :</label>
          <input name="min-price" id="min-price" type="number" value="<%= params["min-price"] %>"/>


          <label for="max-price" class="max-price-label">Max price :</label>
          <input name="max-price" id="max-price" type="number" value="<%= params["max-price"] %>"/>


          <label for="category">Category :</label>
          <select name="category" id="category">
            <% @weapons_category.each do |category| %>
            <% if params[:category] == category %>
            <option value="<%= category %>" selected="selected"><%= category %></option>
            <% else %>
            <option value="<%= category %>"><%= category %></option>
            <% end %>
            <% end %>

            <% if !params[:category].present? || params[:category] == "all" %>
            <option value="all" selected="selected">all</option>
            <% else %>
            <option value="all">all</option>
            <% end %>
          </select>

          <input type="submit" value="Go!" class="btn"/>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="container" style="text-align:center">
  <div class="row" id="weapons-list">
    <% @weapons.each do |weapon| %>
    <div class="col-xs-12 col-sm-4">
      <%= link_to weapon_path(weapon.id) do %>
      <div class="card">
        <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
        url('<%= image_path weapon.photo %>');"></div>
        <div class="card-description">
          <div class="card-price"><%= "#{number_with_delimiter(weapon.price)} €" %></div>
          <div class="card-title"><%= weapon.title %></div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/weapons/show.html.erb
<% content_for :title, "Lord of War - Weapon" %>

<div class="container text-center">

  <div class="row col-xs-12 col-sm-9 col-sm-offset-3 ">

    <h2 class="title">Weapon details<h2>
      <div class="container-card">
        <div class="wrapper">

          <div class="header">
            <div class="price">
              <h1>€ <%= number_with_delimiter(@weapon.price) %> / day </h1>
            </div>
            <div class="heart-wrap">
              <a href="#"><i class="fa heart"></i></a>
            </div>
          </div>

          <div class="product">
            <%= cl_image_tag @weapon.photo,  class: "img"  %>
          </div>

          <div class="info">
            <div class="title">
              <h1><%= @weapon.title %></h1>
              <p><%= @weapon.description %></p>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class= "row col-xs-12 col-sm-3">
      <div class="row">
        <h2 tag="title-book">Book now</h2>
        <div class="container-card-right">
          <div class="wrapper">
            <div>
              <%= simple_form_for @weapon.bookings.build, url: new_weapon_booking_path(@weapon), method: :get do |f| %>
              <%= f.input :start_date, as: :string, input_html: { class: "datepicker"}, label: "Start date"%>
              <%= f.input :end_date, as: :string, input_html: { class: "datepicker"}, label: "End date" %>
              <%= f.submit "Go", class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>

      </div>


      <div class="row">
        <h2 tag="title-owner">Owner</h2>
        <div class="container-card-right">
          <div class="wrapper">

            <div class="avatar-lg">
              <%= image_tag("#{User.find(@weapon.owner_id).avatar_url}") %>
            </div>

            <div class="info">
              <div class="title-user">
                <h3><%= User.find(@weapon.owner_id).last_name%></h3>
                <h4><%= User.find(@weapon.owner_id).first_name %></h4>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>